import React,{useEffect,useMemo,useState}from'react';
import{Alert,Linking,StyleSheet,Text,View}from'react-native';
import{Card,Eyebrow,GoldButton,OutlineButton}from'@/components/ui';
import{colors}from'@/constants/theme';
import{countdownParts,localDiscussionLabel,nextDiscussionDate,type LiveDiscussion}from'@/lib/liveDiscussion';
import{scheduleDiscussionReminder}from'@/lib/notifications';
import{supabase}from'@/lib/supabase';
export default function LiveScreen(){const[discussion,setDiscussion]=useState<LiveDiscussion|null>(null);const[now,setNow]=useState(new Date());useEffect(()=>{supabase.from('live_discussions').select('*').eq('active',true).limit(1).maybeSingle().then(({data})=>data&&setDiscussion(data));const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer);},[]);const next=useMemo(()=>discussion?nextDiscussionDate(discussion,now):null,[discussion,now]);const cd=useMemo(()=>next?countdownParts(next,now):null,[next,now]);async function remind(minutes:number){if(!next)return;try{await scheduleDiscussionReminder(next,minutes);Alert.alert('Reminder set','Your phone will remind you before the next live discussion.');}catch(e){Alert.alert('Could not set reminder',e instanceof Error?e.message:'Please try again.');}}
return <View style={styles.page}>{discussion&&next&&cd?<Card><Eyebrow>NEXT LIVE DISCUSSION</Eyebrow><Text style={styles.title}>{localDiscussionLabel(next)}</Text><Text style={styles.note}>Shown in your local time zone</Text><View style={styles.countdown}>{[['DAYS',cd.days],['HRS',cd.hours],['MIN',cd.minutes],['SEC',cd.seconds]].map(([label,value])=><View key={String(label)} style={styles.timeBox}><Text style={styles.timeNum}>{String(value).padStart(2,'0')}</Text><Text style={styles.timeLabel}>{label}</Text></View>)}</View><View style={styles.buttons}><GoldButton title="Enter Zoom Call Here" onPress={()=>Linking.openURL(discussion.zoom_url)}/><OutlineButton title="Remind Me" onPress={()=>Alert.alert('Choose a reminder','When should we remind you?',[{text:'24 hours before',onPress:()=>remind(1440)},{text:'1 hour before',onPress:()=>remind(60)},{text:'15 minutes before',onPress:()=>remind(15)},{text:'At start time',onPress:()=>remind(0)},{text:'Cancel',style:'cancel'}])}/></View></Card>:<Text style={styles.loading}>Loading the next discussion…</Text>}</View>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.charcoal,padding:20,paddingTop:52},title:{color:colors.text,fontSize:25,fontWeight:'900',lineHeight:31},note:{color:colors.muted,fontSize:12,fontWeight:'700',marginTop:4},countdown:{flexDirection:'row',gap:8,marginVertical:18},timeBox:{flex:1,backgroundColor:colors.panel2,borderRadius:14,paddingVertical:12,alignItems:'center'},timeNum:{color:colors.gold,fontSize:24,fontWeight:'900'},timeLabel:{color:colors.muted,fontSize:9,letterSpacing:1.5,fontWeight:'800'},buttons:{gap:10},loading:{color:colors.muted}});
