import React, { useEffect, useRef, useState } from 'react';
import { FlatList, Image, Linking, StyleSheet, Text, View } from 'react-native';
import { Card, Eyebrow, GoldButton } from '@/components/ui';
import { colors } from '@/constants/theme';
import { supabase } from '@/lib/supabase';
type Video={videoId:string;title:string;thumbnail?:string;channelTitle?:string;watchUrl:string};
export default function VideosScreen(){const[videos,setVideos]=useState<Video[]>([]);const[index,setIndex]=useState(0);const[width,setWidth]=useState(0);const list=useRef<FlatList<Video>>(null);
  useEffect(()=>{supabase.functions.invoke('random-youtube-video',{body:{}}).then(({data,error})=>{if(data&&!error)setVideos((Array.isArray(data.videos)?data.videos:[data]).slice(0,3));});},[]);
  useEffect(()=>{if(videos.length<2||!width)return;const timer=setInterval(()=>setIndex(current=>{const next=(current+1)%videos.length;list.current?.scrollToOffset({offset:next*width,animated:true});return next;}),3000);return()=>clearInterval(timer);},[videos.length,width]);
  return <View style={styles.page}><Eyebrow>SOMETHING WORTH THINKING ABOUT</Eyebrow><Text style={styles.title}>Long-form videos from Try Jesus Media.</Text><View onLayout={e=>setWidth(e.nativeEvent.layout.width)}><FlatList ref={list} data={videos} keyExtractor={v=>v.videoId} horizontal pagingEnabled showsHorizontalScrollIndicator={false} onMomentumScrollEnd={e=>width&&setIndex(Math.round(e.nativeEvent.contentOffset.x/width))} renderItem={({item})=><View style={{width:width||undefined}}><Card style={styles.card}>{item.thumbnail?<Image source={{uri:item.thumbnail}} style={styles.image}/>:null}<Text style={styles.name}>{item.title}</Text><Text style={styles.meta}>{item.channelTitle??'Try Jesus Media'}</Text><GoldButton title="Watch Now" onPress={()=>Linking.openURL(item.watchUrl)}/></Card></View>}/></View><View style={styles.dots}>{videos.map((v,i)=><View key={v.videoId} style={[styles.dot,index===i&&styles.activeDot]}/>)}</View></View>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.charcoal,padding:20,paddingTop:52},title:{color:colors.text,fontSize:25,fontWeight:'900',lineHeight:31,marginBottom:16},card:{padding:14},image:{width:'100%',aspectRatio:16/9,borderRadius:14,backgroundColor:colors.plum,marginBottom:14},name:{color:colors.text,fontSize:19,fontWeight:'900',lineHeight:25,marginBottom:6},meta:{color:colors.muted,fontSize:13,marginBottom:14},dots:{flexDirection:'row',justifyContent:'center',gap:7,marginTop:12},dot:{width:7,height:7,borderRadius:4,backgroundColor:colors.border},activeDot:{width:18,backgroundColor:colors.gold}});
